const corners = (rx, ry = rx) => Object.freeze([
  Object.freeze({ rx, ry }),
  Object.freeze({ rx, ry }),
  Object.freeze({ rx, ry }),
  Object.freeze({ rx, ry }),
]);

const shapes = (...values) => Object.freeze(values.length === 1
  ? [values[0], values[0], values[0], values[0]]
  : values);

const solid = (color) => Object.freeze({ kind: "solid", color });

const blendRaster = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAABkCAYAAAABtjuPAAABe0lEQVR42u3SQQ2AMBAAwfrj2x9BCd4w0QQHNVADxcNxyX3msQY201Y/d2b9fVLb40rtuGdq/v2rGQgggAACaCCAAAIIoIEAAggggAYCCCCAABoIIIAAAmgggAACCKCBAAIIIIAGAggggAAC6B+AAAIIoH8hgMAAU/kPQAABBBBAAwEEEEAADQQQQAABNBBAAAEE0EAAAQQQQAMBBBBAAA0EEEAAATQQQAABBBBA/wAEEEAA/YsBBAaYyn8AAggggAAaCCCAAAJoIIAAAgiggQACCCCABgIIIIAAGggggAACaCCAAAIIoIEAAggggAD6ByCAAALoXwwgMMBU/gMQQAABBNBAAAEEEEADAQQQQAANBBBAAAE0EEAAAQTQQAABBBBAAwEEEEAADQQQQAABBNA/AAEEEED/YgCBAabyH4AAAggggAYCCCCAABoIIIAAAmgggAACCKCBAAIIIIAGAggggAAaCCCAAAJoIIAAAggggP4BCCCAAPoX6gNlH7bAXGC7VAAAAABJRU5ErkJggg==";

const gradient = Object.freeze({
  kind: "linear-gradient",
  css: "linear-gradient(135deg, #75f6ff 0%, #2757d7 52%, #172a73 100%)",
  from: Object.freeze([0, 0]),
  to: Object.freeze([1, 1]),
  stops: Object.freeze([
    Object.freeze([0, "#75f6ff"]),
    Object.freeze([0.52, "#2757d7"]),
    Object.freeze([1, "#172a73"]),
  ]),
});

export const ORACLE_CASE_SCHEMA = "cornerfill-oracle-case@1";

export const oracleCases = Object.freeze([
  Object.freeze({
    id: "bevel",
    description: "Symmetric bevel keyword on an opaque solid fill",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "bevel",
    shapeParameters: shapes(0),
    paint: solid("#f05a47"),
  }),
  Object.freeze({
    id: "round",
    description: "Ordinary round corner baseline",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "round",
    shapeParameters: shapes(1),
    paint: gradient,
  }),
  Object.freeze({
    id: "squircle",
    description: "Convex exponent-four squircle",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "58px",
    radii: corners(58),
    shapeCss: "squircle",
    shapeParameters: shapes(2),
    paint: solid("#6f5cff"),
  }),
  Object.freeze({
    id: "scoop",
    description: "Concave scoop keyword",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "scoop",
    shapeParameters: shapes(-1),
    paint: solid("#20bb86"),
  }),
  Object.freeze({
    id: "notch",
    description: "Concave limiting notch keyword",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "42px",
    radii: corners(42),
    shapeCss: "notch",
    shapeParameters: shapes(Number.NEGATIVE_INFINITY),
    paint: solid("#f5bf38"),
  }),
  Object.freeze({
    id: "superellipse-positive",
    description: "Arbitrary finite convex superellipse parameter",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "58px 42px / 44px 62px",
    radii: Object.freeze([
      Object.freeze({ rx: 58, ry: 44 }),
      Object.freeze({ rx: 42, ry: 62 }),
      Object.freeze({ rx: 58, ry: 44 }),
      Object.freeze({ rx: 42, ry: 62 }),
    ]),
    shapeCss: "superellipse(3)",
    shapeParameters: shapes(3),
    paint: gradient,
  }),
  Object.freeze({
    id: "superellipse-negative",
    description: "Arbitrary finite concave superellipse parameter",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "52px",
    radii: corners(52),
    shapeCss: "superellipse(-1.5)",
    shapeParameters: shapes(-1.5),
    paint: solid("#e75ca8"),
  }),
  Object.freeze({
    id: "mixed-asymmetric",
    description: "Four shape values and asymmetric elliptical radii",
    size: Object.freeze([230, 170]),
    captureSize: Object.freeze([310, 250]),
    radiusCss: "64px 34px 52px 24px / 34px 58px 28px 46px",
    radii: Object.freeze([
      Object.freeze({ rx: 64, ry: 34 }),
      Object.freeze({ rx: 34, ry: 58 }),
      Object.freeze({ rx: 52, ry: 28 }),
      Object.freeze({ rx: 24, ry: 46 }),
    ]),
    shapeCss: "squircle bevel scoop round",
    shapeParameters: shapes(2, 0, -1, 1),
    paint: gradient,
  }),
  Object.freeze({
    id: "zero-radius",
    description: "Zero radius makes corner-shape visually inert",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "0",
    radii: corners(0),
    shapeCss: "notch",
    shapeParameters: shapes(Number.NEGATIVE_INFINITY),
    paint: solid("#db6644"),
  }),
  Object.freeze({
    id: "border-round",
    description: "Uniform solid border and round inner contour",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "round",
    shapeParameters: shapes(1),
    border: Object.freeze({ width: 10, color: "#f4efdf" }),
    paint: solid("#473bbf"),
  }),
  Object.freeze({
    id: "border-shaped-unequal",
    description: "One-color solid border with unequal widths and four corner shapes",
    size: Object.freeze([230, 170]),
    captureSize: Object.freeze([310, 250]),
    radiusCss: "64px 34px 52px 24px / 34px 58px 28px 46px",
    radii: Object.freeze([
      Object.freeze({ rx: 64, ry: 34 }),
      Object.freeze({ rx: 34, ry: 58 }),
      Object.freeze({ rx: 52, ry: 28 }),
      Object.freeze({ rx: 24, ry: 46 }),
    ]),
    shapeCss: "squircle bevel scoop notch",
    shapeParameters: shapes(2, 0, -1, Number.NEGATIVE_INFINITY),
    border: Object.freeze({
      widths: Object.freeze([8, 16, 22, 5]),
      color: "#f4efdf",
    }),
    paint: solid("#473bbf"),
  }),
  Object.freeze({
    id: "inset-shadow-shaped",
    description: "Contained zero-blur inset shadow follows a shaped inner contour",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "56px",
    radii: corners(56),
    shapeCss: "squircle",
    shapeParameters: shapes(2),
    boxShadow: "inset 0 0 0 14px rgba(244, 239, 223, 0.82)",
    paint: solid("#473bbf"),
  }),
  Object.freeze({
    id: "outline-contained-shaped",
    description: "Negative-offset solid outline stays inside a shaped border box",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "52px",
    radii: corners(52),
    shapeCss: "bevel",
    shapeParameters: shapes(0),
    outline: Object.freeze({ width: 10, style: "solid", color: "#f4efdf", offset: -10 }),
    paint: solid("#473bbf"),
  }),
  Object.freeze({
    id: "opposite-concave-overlap",
    description: "Diagonal concave hull constraint regression",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "118px 18px 118px 18px / 92px 18px 92px 18px",
    radii: Object.freeze([
      Object.freeze({ rx: 118, ry: 92 }),
      Object.freeze({ rx: 18, ry: 18 }),
      Object.freeze({ rx: 118, ry: 92 }),
      Object.freeze({ rx: 18, ry: 18 }),
    ]),
    shapeCss: "scoop round scoop round",
    shapeParameters: shapes(-1, 1, -1, 1),
    paint: solid("#1db6c9"),
    nativeOracleLimitation: "Chromium path intersection differs from the CSSWG opposite-corner hull scale",
  }),
  Object.freeze({
    id: "interpolation-midpoint",
    description: "Caller-clocked scoop-to-squircle midpoint in diagonal-intersection space",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "52px",
    radii: corners(52),
    shapeCss: "superellipse(0.28833415474651186)",
    shapeParameters: shapes(0.28833415474651186),
    interpolation: Object.freeze({ from: "scoop", to: "squircle", progress: 0.5 }),
    paint: solid("#ed6f32"),
  }),
  Object.freeze({
    id: "bevel-rotated",
    description: "Bevel surface under compound 3D rotation",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([340, 300]),
    radiusCss: "50% 50% 0 0 / 100% 100% 0 0",
    radii: Object.freeze([
      Object.freeze({ rx: 110, ry: 160 }),
      Object.freeze({ rx: 110, ry: 160 }),
      Object.freeze({ rx: 0, ry: 0 }),
      Object.freeze({ rx: 0, ry: 0 }),
    ]),
    shapeCss: "bevel bevel round round",
    shapeParameters: shapes(0, 0, 1, 1),
    transform: "rotateX(31deg) rotateY(47deg) rotateZ(13deg)",
    perspective: 600,
    paint: gradient,
  }),
  Object.freeze({
    id: "mario-texel-face",
    description: "Real 4 by 4 Mario texel field stretched across one retained face",
    size: Object.freeze([64, 44]),
    captureSize: Object.freeze([160, 140]),
    radiusCss: "50% 50% 0 0 / 100% 100% 0 0",
    radii: Object.freeze([
      Object.freeze({ rx: 32, ry: 44 }),
      Object.freeze({ rx: 32, ry: 44 }),
      Object.freeze({ rx: 0, ry: 0 }),
      Object.freeze({ rx: 0, ry: 0 }),
    ]),
    shapeCss: "bevel bevel round round",
    shapeParameters: shapes(0, 0, 1, 1),
    paint: Object.freeze({
      kind: "image",
      url: "/__mario/texels.webp",
      sourceSize: Object.freeze([4852, 3280]),
      backgroundSize: Object.freeze([77632, 36080]),
      backgroundPosition: Object.freeze([-448, 0]),
      repeat: "no-repeat",
    }),
    sourceEvidence: Object.freeze({
      faceIndex: 7,
      field: Object.freeze({ x: 28, y: 0, width: 4, height: 4 }),
      css: "width:64px;height:44px;background-size:77632px 36080px;background-position:-448px 0",
    }),
  }),
  Object.freeze({
    id: "raster-repeat-origin",
    description: "Atlas raster with round repeat and content-box origin and clip",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    padding: "14px 20px 18px 12px",
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "bevel",
    shapeParameters: shapes(0),
    paint: Object.freeze({
      kind: "image",
      url: "/__mario/texels.webp",
      sourceSize: Object.freeze([4852, 3280]),
      backgroundSize: "34px auto",
      backgroundPosition: "center bottom 8px",
      repeat: "round no-repeat",
      origin: "content-box",
      clip: "content-box",
    }),
  }),
  Object.freeze({
    id: "background-blend-multiply",
    description: "One static opaque raster multiplies over one opaque background color",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    radiusCss: "48px",
    radii: corners(48),
    shapeCss: "bevel",
    shapeParameters: shapes(0),
    paint: Object.freeze({
      kind: "image",
      url: blendRaster,
      sourceSize: Object.freeze([160, 100]),
      backgroundSize: Object.freeze([160, 100]),
      backgroundPosition: "center",
      repeat: "no-repeat",
      origin: "border-box",
      clip: "border-box",
      blendMode: "multiply",
      color: "#734cc4",
      opaque: true,
    }),
  }),
  Object.freeze({
    id: "gradient-layers",
    description: "Linear, radial, conic, and atlas layers in CSS paint order",
    size: Object.freeze([220, 160]),
    captureSize: Object.freeze([300, 240]),
    padding: "10px 14px 16px 8px",
    radiusCss: "58px 34px 52px 24px / 44px 58px 28px 46px",
    radii: Object.freeze([
      Object.freeze({ rx: 58, ry: 44 }),
      Object.freeze({ rx: 34, ry: 58 }),
      Object.freeze({ rx: 52, ry: 28 }),
      Object.freeze({ rx: 24, ry: 46 }),
    ]),
    shapeCss: "squircle bevel scoop round",
    shapeParameters: shapes(2, 0, -1, 1),
    paint: Object.freeze({
      kind: "layers",
      color: "#14213d",
      layers: Object.freeze([
        Object.freeze({
          kind: "linear-gradient",
          css: "linear-gradient(to bottom right, rgba(117,246,255,.72) 0%, rgba(39,87,215,.08) 52%, rgba(23,42,115,.62) 100%)",
          backgroundSize: "55% 100%",
          backgroundPosition: "left top",
          repeat: "repeat-x",
          origin: "padding-box",
          clip: "content-box",
        }),
        Object.freeze({
          kind: "radial-gradient",
          css: "radial-gradient(ellipse farthest-corner at 32% 68%, rgba(255,244,170,.9) 0%, rgba(232,72,132,.45) 45%, transparent 100%)",
          backgroundSize: "96px 72px",
          backgroundPosition: "right 8px top 10px",
          repeat: "no-repeat",
          origin: "border-box",
          clip: "padding-box",
        }),
        Object.freeze({
          kind: "conic-gradient",
          css: "conic-gradient(from 30deg at 55% 45%, rgba(255,80,60,.55) 0deg, rgba(70,230,130,.45) 120deg, rgba(60,100,255,.55) 240deg, rgba(255,80,60,.55) 1turn)",
          backgroundSize: "60px 60px",
          backgroundPosition: "center",
          repeat: "round space",
          origin: "content-box",
          clip: "border-box",
        }),
        Object.freeze({
          kind: "image",
          url: "/__mario/texels.webp",
          sourceSize: Object.freeze([4852, 3280]),
          backgroundSize: "80px 54px",
          backgroundPosition: "center bottom",
          repeat: "space no-repeat",
          origin: "content-box",
          clip: "border-box",
        }),
      ]),
    }),
  }),
]);

export function getOracleCase(id) {
  return oracleCases.find((entry) => entry.id === id) ?? null;
}
