export const CORNERFILL_SPEC_REVISION = Object.freeze({
  module: "CSS Borders and Box Decorations Level 4",
  workingDraftDate: "2026-03-26",
  editorsDraft: "https://drafts.csswg.org/css-borders-4/",
  sourceCommit: "13b14ec48af0219c893713d670cf80d8c014a648",
  sourceUrl: "https://github.com/w3c/csswg-drafts/blob/13b14ec48af0219c893713d670cf80d8c014a648/css-borders-4/Overview.bs",
  wptCommit: "4a5810a124fa0523dd2494996bf1542d4b67f394",
});

export type CornerfillPropertySupport = "automatic" | "native-computed" | "not-implemented";

export const CORNERFILL_PROPERTY_SUPPORT = Object.freeze({
  automatic: Object.freeze([
    "corner-shape",
    "corner-top-left-shape",
    "corner-top-right-shape",
    "corner-bottom-right-shape",
    "corner-bottom-left-shape",
    "corner-start-start-shape",
    "corner-start-end-shape",
    "corner-end-end-shape",
    "corner-end-start-shape",
  ] as const),
  nativeComputed: Object.freeze([
    "border-radius",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius",
    "border-start-start-radius",
    "border-start-end-radius",
    "border-end-end-radius",
    "border-end-start-radius",
  ] as const),
  notImplemented: Object.freeze([
    "corner-top-shape",
    "corner-right-shape",
    "corner-bottom-shape",
    "corner-left-shape",
    "corner-block-start-shape",
    "corner-block-end-shape",
    "corner-inline-start-shape",
    "corner-inline-end-shape",
    "corner-top-left",
    "corner-top-right",
    "corner-bottom-right",
    "corner-bottom-left",
    "corner-start-start",
    "corner-start-end",
    "corner-end-end",
    "corner-end-start",
    "corner-top",
    "corner-right",
    "corner-bottom",
    "corner-left",
    "corner-block-start",
    "corner-block-end",
    "corner-inline-start",
    "corner-inline-end",
    "corner",
    "border-top-radius",
    "border-right-radius",
    "border-bottom-radius",
    "border-left-radius",
    "border-block-start-radius",
    "border-block-end-radius",
    "border-inline-start-radius",
    "border-inline-end-radius",
  ] as const),
  targets: Object.freeze({
    elements: "automatic",
    pseudoElements: "not-implemented",
  }),
});
